name: build-sphinx-rtd

on:
  push:
    branches: [ "main" ]

jobs:  
  build:
    runs-on: ubuntu-latest
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      
      - name: Install dependencies
        run: pip install numpy sphinx sphinx_rtd_theme

      - name: Sphinx build
        run: sphinx-build docs/source docs/build

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v4
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: html
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build
          force_orphan: true
